### ISSUE TITLE
Plugin does not work on RPi4

### ISSUE THREAD

**Issue by gelse** [matthuisman/plugin.program.noobs.companion#4]
... as the title says ...

**Comment by matthuisman** [comment]
What is error / issue.
Please provide debug log.
https://kodi.wiki/view/Log_file/Easy

**Comment by gelse** [comment]
Sorry for the short description, i was in a hurry.
 It just says the plugin is only working on Raspberry pi - i guess the distribution/architecture recognition is somehow missing the rpi4, or it is libreelec.
 I will provide a debug log asap, but that could take until the weekend.

Tue Aug 06 22:37:21 GMT+02:00 2019 Matt Huisman <notifications@github.com>:

**Comment by matthuisman** [comment]
Oh, its just giving that error and failing to start?
That should be easily fixed.
Your using LibreELEC on RPI4?

**Comment by matthuisman** [comment]
```
    if not xbmc.getCondVisibility('System.Platform.Linux.RaspberryPi'):
        dialog.ok("Not Supported", 'This addon only works on the Raspberry Pi range of boards.')
        sys.exit(0)
```

Is that the error you get?
"This addon only works on the Raspberry Pi range of boards."

If so, then I think it's a kodi bug.
as System.Platform.Linux.RaspberryPi should be set for the Rpi4

**Comment by gelse** [comment]
Yes, exactly. To both your questions. ;-)

Tue Aug 06 22:52:43 GMT+02:00 2019 Matt Huisman <notifications@github.com>:

**Comment by gelse** [comment]
Hmmm... I thought the wording was slightly different, i'll have a look tomorrow.

Tue Aug 06 22:53:48 GMT+02:00 2019 Matt Huisman <notifications@github.com>:

**Comment by matthuisman** [comment]
Maybe it was
"The supported systems are:\nLibreELEC, OpenELEC, OSMC & Xbian"

We don't get the PI4 in NZ until October, so I'm unable to test :(

**Comment by matthuisman** [comment]
Just pushed 0.5.8 of this add-on that should fix this issue.
It simply has the check for raspberry pi removed.
https://github.com/matthuisman/plugin.program.noobs.companion/commit/44f01ef937986fa99f2bd30fd763b5eb5b5ac775

As per here:
https://forum.kodi.tv/showthread.php?tid=346077&pid=2875293#pid2875293

Let me know if that doesn't fix it and i'll re-open issue

**Comment by adz21c** [comment]
Hi,
This is still not working for me. I've just installed 0.5.9, so never got the above message. I seem to be able to configure the default boot and have yet to check if setting boot back was successful.

On selecting an OS during reboot I can just see a faded dialog saying "Cmd failed reboot 6", sometimes, which ultimately reboots back into the default boot.

I tried running part_reboot directly (just to note, no idea what I am doing ;-) ) and I get the message /etc/init.d/rcK and /etc/init.d/rc 0 not found. Looks like libreelec is running SystemD.

If you need any more information or to test anything, drop me a message :-)

Thanks,
Adam

**Comment by matthuisman** [comment]
@adz21c
I'll take a look.
I now have a Pi4 so can actually test :)

**Comment by matthuisman** [comment]
After a quick look, I think part rebooting is broken on the Pi4.
This would require it to be fixed in the Pi4 firmware.
Just going to try in Raspbian to confirm

**Comment by matthuisman** [comment]
OK, confirmed it's a problem with RPI4 and NOOBS / PINN
Probably something overlooked in the firmware or something.
I have opened an issue with them here:
https://github.com/raspberrypi/noobs/issues/551

Closing this issue
